### ISSUE TITLE
An incorrect command does nothing

### ISSUE THREAD

**Issue by jnovack** [mattgreen/fogeybot#10]
> [3:33 PM] Jeffh934: !register

FogeyBot says nothing.

I would expect:

> [3:33 PM] Jeffh934: !register
> [3:36 PM] FogeyBot: 
>     Registers/updates your battle tag
>     !register <battletag>

If FogeyBot has admin permissions, I'd optionally want him to REMOVE the bad message (from another user) so that other users don't copy the bad message.

**Comment by mattgreen** [comment]
Not worth the complexity it adds.
