### ISSUE TITLE
DISCORD_CLIENT_ID - no longer needed

### ISSUE THREAD

**Issue by jhgg** [mattgreen/fogeybot#14]
Hey, saw your tweet with the bot. Awesome stuff!

We've just added the ability for you to grab the Discord Application info using the bot's token (which means that you can grab the client ID using the bot's token). It's not in the docs yet, but this issue explains the change:

https://github.com/hammerandchisel/discord-api-docs/issues/27

**Comment by mattgreen** [comment]
Thanks!

To be clear, we don't need to specify the client ID at all? I didn't know if I could get away with only specifying the token. (I'm not using it for anything at the moment.)

**Comment by jhgg** [comment]
Nope. Not needed.
