### ISSUE TITLE
Pickup MMR Calculations

### ISSUE THREAD

**Issue by jnovack** [mattgreen/fogeybot#16]
Pickup MMRs should be a weighted average of Team League, Hero League and Quick Match.

It would take some tweaking to figure out the best formula, but highest MMR should weight the highest.  A number of players have lower QM rating than their HL or TeamLeague ratings.  Pickups tend to be more Team League related (because of the 5-man coordination and voice chat) than QM related.

Perhaps:
- `(HighestMMR * .57) + (MidestMMR * .26) + (LowestMMR * 17)` or 
- `(HighestMMR * .75) + (LowestMMR * .75)`

**Comment by mattgreen** [comment]
I agree this could be better.

I want to do something like this, where the weights themselves are weighted by number of games played in that category. But, I don't know of a way to get that data from HotsLogs. I don't want to ascribe a bunch of weight to a category the player rarely plays.

**Comment by jnovack** [comment]
maybe not the number of games per category, but use the league as an indication of the "truthiness" of the mmr.

In order to be placed into a certain league, you have to have a certain number of games (more than the 20 required).  Thus, in [Poe's instance](https://www.hotslogs.com/API/Players/1/homeofpoe_1289), he does not have a MMR for TL, so don't count it.  But in [my instance](https://www.hotslogs.com/API/Players/1/ticklemeozmo_1973), I do, so you can (and probably should, since it's the highest MMR).

An additional factor is MMR does not scale linearly. A 300 point difference between 900 and 1200 is FAR different than 2600 to 2900.  Higher MMRs might need more weight.
