### ISSUE TITLE
Balance this game better?

### ISSUE THREAD

**Issue by jnovack** [mattgreen/fogeybot#18]
This is just an exercise to track the progress on how we can balance this game better.  This was a completely imbalanced game (not FogeyBot's fault), but what CAN Fogeybot do to make it better?  

```
Team 1 (avg MMR: 2119) :
   2950 - Razoth
   2371 - TickleMeOzmo
   1818 - Kendo
   1738 - katrinalorien
   1719 - Cercie
Team 2 (avg MMR: 1931) :
   2439 - VelveThunder
   2388 - syrowatts
   1799 - drivelikebrazil
   1761 - TOFTS
   1269 - bray
```

**Using THESE numbers, how could this game be better (or differently) matched?**

**Comment by jnovack** [comment]
First thing to notice, is that FogeyBot did not make the most balanced team possible.  The most balanced team possible, with an average MMR of 2025 vs 2025.4 is:

`Razoth, TickleMeOzmo, Kendo, Cercie, bray`
`VelveThunder, syrowatts, drivelikebrazil, TOTFS, katrinalorien`

I had to manually do this.  But how can we do this programmatically without running through 10! (that's 10 factorial) permutations?

**Comment by mattgreen** [comment]
Changing the balance algorithm to assign the higher-rated player to the lower-average MMR team (as @jamonholmgren suggested) gave me similar results:

Team 1: bray, katrinalorien, drivelikebrazil, TickleMeOzmo, Razoth (avg MMR: 2025)
Team 2: Cercie, TOFTS, Kendo, syrowatts, VelveThunder (avg MMR: 2025)

It's remarkable that these teams can be this even in the first place, given the data.

**Comment by jnovack** [comment]
I think this was just a fluke that both teams managed to get 2025. Sheer coincidence.

**Comment by mattgreen** [comment]
Fixed in 304b01f37601058f99c144660b523c6aa3c62ea8.

Test data added to test suite, as well. Thanks!

**Comment by jamonholmgren** [comment]
Just kind of brute-forcing it?

**Comment by mattgreen** [comment]
Yeah. I don't know if it is better than the "assign highest ranked player to lowest-average MMR team" algorithm we discussed previously, but brute-forcing it kinda guarantees we get the best possibility by the measured conditions.
