### ISSUE TITLE
Super Noob Questions

### ISSUE THREAD

**Issue by YPowTecH** [mattgreen/fogeybot#19]
I have a lot of questions:
1. Discord bot user and client ID: Meaning like get carbon bot?
2. What and where is the DISCORD_TOKEN
3. MonoDB do we need that because it requires a trial (didnt look very hard)

Thanks

**Comment by mattgreen** [comment]
You do need MongoDB, as it's used to store the MMRs/battle tags offline.

Discord's bot user and token is issued by the Discord API. If these terms are unfamiliar, you'll want to read through the [https://discordapp.com/developers/docs/intro](Discord Developer Guide).
