### ISSUE TITLE
HotsLogs integration

### ISSUE THREAD

**Issue by mattgreen** [mattgreen/fogeybot#2]
Users should be able to register their battle tags with the bot:

`!register user#1291`

Then when they join, the bot should pull their MMR from HotsLogs automatically. It'd be nice if this was cached and it auto-updated periodically.

**Comment by homeofpoe** [comment]
FYI I checked with /u/barrett777, hotslogs creator, and he said this:

Hello,
I do have a player MMR API:
This takes a player's 'PlayerID' from HOTS Logs, which you can find in their profile: https://www.hotslogs.com/API/Players/1
You can also use a player's Region and BattleTag: https://www.hotslogs.com/API/Players/1/Benthor_1644
1 = US
2 = EU
3 = KR
5 = CN
You're welcome to use these if you want :)
Thanks, Ben
