### ISSUE TITLE
Captain's Draft

### ISSUE THREAD

**Issue by jnovack** [mattgreen/fogeybot#20]
Like `!startpickup` proposing `!startdraft`
- Would let 10 people join a pickup.
- Pick the top 2 MMRs as "Captains".
- Team 1 gets First player pick.
- Team 2 gets First hero pick.
- Do NOT divide into teams.  FogeyBot picks the two captains (MMR) and the 8 players.

```
FogeyBot: Captain assignments: 
Team 1: Pluralmango
Team 2: syrowatts

Players: Krezrel, TOFTS, katrinalorien, Hulk, drivelikebrazil, bray, Shadowleaves, Kendo
```

**Comment by jnovack** [comment]
let them still `!joinpickup` because users are stupid.

**Comment by mattgreen** [comment]
So captains manually form teams?

**Comment by jnovack** [comment]
Yes, the _raison d'etre_ was that fundamentally (the same MMR'd) 10 people were playing pickup games, and FogeyBot was consistently putting the same people on the same teams.

This lead to one side being "OP" because of synergy, team players on the same team, etc.  It was known before the actual drafting who would have won the game, despite FogeyBot saying that the "MMRs were equal".

To alleviate this concern, we wanted to have a "Captain's Draft", BUT restrict it to the first 10 players who responded (in the event that 11 or 12 wanted to play).  FogeyBot would restrict it to the first 10, print out the captains and let humans do the work from there.

We attempted to manually do a captains draft using FogeyBot's `!startpickup` but that lead to an issue where someone wasn't picked, because one of the captains was an artard, and didn't sign up for the draft letting in an 11th player and hurting people's feelings.
