### ISSUE TITLE
Extend to also support Overwatch

### ISSUE THREAD

**Issue by zoidyzoidzoid** [mattgreen/fogeybot#22]
Hey there.

Before I dig too deep into the code, I was wondering if you'd be interested in supporting Overwatch, or would it be better for me to fork it and customise that independently?

**Comment by mattgreen** [comment]
I'd be down for this but I'd like to extend it such that we can cleanly encapsulate the notion of which game it is well.

So, hack away, but be warned I'll have some opinions when it comes to integrating it all. :)

**Comment by zoidyzoidzoid** [comment]
Awesome, thanks. Yeah, a easily extendable Game-type model would be awesome. 

I've gone with [discord-gather](https://github.com/veryhappythings/discord-gather) since it was less tied to a game-specific API for now.

**Comment by mattgreen** [comment]
Good luck! I'll mull this over but it's probably pretty low on the priority list.
